FROM apache/airflow:2.10.5

USER root
RUN apt-get update && \
    apt-get install -y curl wget openjdk-17-jdk python3-pip && \
    wget -qO - https://archive.apache.org/dist/spark/spark-3.4.0/spark-3.4.0-bin-hadoop3.tgz | tar -xz -C /opt/ && \
    ln -sf /opt/spark-3.4.0-bin-hadoop3 /opt/spark && \
    ln -sf /opt/spark/bin/spark-submit /usr/local/bin/spark-submit

USER airflow
ENV SPARK_HOME=/opt/spark
